Added the is_smaller/is_greater sound reproduction code. Close #8
literacyapp-org/nyas-space-quest-qd pull request #9
Opened 2017-06-23 05:10 UTC by protito

2017-06-23 09:37 UTC, jo-elimu requested changes

2017-06-23 09:37 UTC, jogrimst commented on Classes/InfoStop.cpp
> +        string greaterOrSmaller = "/is_greater_than.wav";
@protito To achieve some variation, can we randomly select either `is_greater_than.wav` or `is_larger_than.wav`?

2017-06-29 03:48 UTC, protito commented on Classes/InfoStop.cpp
> +        string greaterOrSmaller = "/is_greater_than.wav";
Sure, done.

2017-06-29 12:15 UTC, jo-elimu approved these changes

2017-06-29 12:15 UTC, merged